
# Creating a group file with mris_preproc (created the following out of this )
#the tssh file should in FS directory
#run the following with tcsh runMrisPreproc.sh

#!/bin/tcsh
setenv study $argv[1]

foreach hemi (lh rh)
  foreach smoothing (10)
    foreach meas (volume thickness)
      mris_preproc --fsgd FSGD/{$study}.fsgd \ #FSGD file
        --cache-in {$meas}.fwhm{$smoothing}.fsaverage \ #input files
        --target fsaverage \  #target template
        --hemi {$hemi} \ #which hemi, left or right
        --out {$hemi}.{$meas}.{$study}.{$smoothing}.mgh #output name
    end
  end
end




#Fitting the general linear model with mri_glmfit (created the following out of this )
#run the following with tcsh runGLMs.sh

#!/bin/tcsh

set study = $argv[1]

foreach hemi (lh rh)
  foreach smoothness (10)
    foreach meas (volume thickness)
        mri_glmfit \
        --y {$hemi}.{$meas}.{$study}.{$smoothness}.mgh \ #input file generated by mris_preproc
        --fsgd FSGD/{$study}.fsgd \
        --C group.diff.mtx \
        --C group-x-age.mtx \
        --C group-x-weight.mtx \
        --C group-x-age-x-weight.mtx \
        --C g1g2.intercept.mtx \
        --C g1g2.age.mtx
        --surf fsaverage {$hemi}  \ #The hemisphere of the template to analyze
        --cortex  \  #A mask to restrict our analysis only to the cortex
        --glmdir {$hemi}.{$meas}.{$study}.{$smoothness}.glmdir #output directories name
    end
  end
end
#in each results directory: The file gamma.mgh is a contrast map; z.mgh converts this contrast into a z-map,
# and sig.mgh converts the contrast into a map of p-values.
#FreeSurfer uses -log10(p) notation; in other words, a value of 1 in the sig.mgh map represents a p-value of 0.1, 
#a value of 2 represents a p-value of 0.01, and so on.




#Cluster Correction with mri_glmfit-sim (created the following out of this )

#!/bin/tcsh

setenv study $argv[1]

foreach meas (thickness volume)
  foreach hemi (lh rh)
    foreach smoothness (10)
      foreach dir ({$hemi}.{$meas}.{$study}.{$smoothness}.glmdir)
        mri_glmfit-sim \
          --glmdir {$dir} \
          --cache 3.0 pos \ # The vertex-wise cluster threshold, can be changed from 1.3 to 4.0, better greater than 3;
          --cwp 0.05  \ #The cluster-wise p-threshold, keep default
          --2spaces #Correction for analyzing both hemispheres, keep default
      end
    end
  end
end
#in results, mainly focus on *.cluster.summary and *.cluster.mgh files